# This is a basic workflow to help you get started with Actions
name: Compile and Publish Artifact

on:
  pull_request:
    branches:
      - '*'
      - '!main'
      - 'service*'
  push:
    branches:
      - '*'
      - '!main'
      - 'service*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '19'
    - name: Build with Maven
      run: mvn -B install
    - name: Read Pom
      id: read-pom
      run: |
        module_path=$(sed -n "/<module>.*${GITHUB_REF#refs/heads/}.*<\/module>/p" pom.xml | sed 's/<module>\(.*\)<\/module>/\1/')
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}/${{ steps.read-pom.outputs.module-path }}/target/${GITHUB_REF#refs/heads/}.jar
